# QistManager full domain schema.
# Each entry becomes one migration: db/migrate/001_create_<table>.rb
#
#   columns: [name, type, options]
#   money columns default to numeric(15,2); dates to date; timestamps always added.

TABLES = [
  # ------------------------------------------------------------------ core
  {
    table: "businesses",
    columns: [
      [:name, :string, { null: false }],
      [:business_type, :string, { default: "Automobile Dealership" }],
      [:phone, :string],
      [:address, :text],
      [:city, :string],
      [:cnic, :string],
      [:ntn, :string],
      [:logo_filename, :string],
      [:currency, :string, { default: "PKR" }],
      [:default_installment_day, :integer, { default: 10 }],
      [:late_fee_type, :string, { default: "none" }],
      [:late_fee_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:low_stock_alert, :integer, { default: 5 }],
      [:allow_negative_stock, :boolean, { default: false }],
    ],
  },
  {
    table: "users",
    columns: [
      [:full_name, :string, { null: false }],
      [:username, :string, { null: false }],
      [:password_digest, :string, { null: false }],
      [:role, :string, { default: "staff", null: false }],
      [:phone, :string],
      [:status, :string, { default: "active", null: false }],
      [:last_login_at, :datetime],
      [:must_change_password, :boolean, { default: false }],
      [:failed_login_count, :integer, { default: 0 }],
      [:locked_until, :datetime],
    ],
    indexes: [
      ["users", ["username"], { unique: true, name: "index_users_on_username" }],
    ],
  },
  {
    table: "payment_modes",
    columns: [
      [:name, :string, { null: false }],
      [:is_cash, :boolean, { default: false }],
      [:status, :string, { default: "active" }],
      [:sort_order, :integer, { default: 0 }],
    ],
  },
  {
    table: "expense_categories",
    columns: [
      [:name, :string, { null: false }],
      [:status, :string, { default: "active" }],
    ],
  },

  # -------------------------------------------------------------- catalogue
  {
    table: "brands",
    columns: [
      [:name, :string, { null: false }],
      [:status, :string, { default: "active", null: false }],
    ],
    indexes: [["brands", ["name"], { unique: true }]],
  },
  {
    table: "categories",
    columns: [
      [:name, :string, { null: false }],
      [:category_type, :string, { default: "vehicle", null: false }],
      [:serial_no, :string],
      [:warranty_months, :integer, { default: 0 }],
      [:status, :string, { default: "active", null: false }],
    ],
  },
  {
    table: "products",
    columns: [
      [:brand_id, :bigint, { null: false }],
      [:category_id, :bigint, { null: false }],
      [:name, :string, { null: false }],
      [:status, :string, { default: "active", null: false }],
    ],
    indexes: [
      ["products", ["brand_id"]],
      ["products", ["category_id"]],
      ["products", ["name"]],
    ],
  },
  {
    table: "variants",
    columns: [
      [:product_id, :bigint, { null: false }],
      [:attribute_name, :string, { default: "Model" }],
      [:value, :string, { null: false }],
      [:purchase_price, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:sale_price, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:status, :string, { default: "active", null: false }],
    ],
    indexes: [
      ["variants", ["product_id"]],
      ["variants", ["value"]],
    ],
  },
  {
    table: "suppliers",
    columns: [
      [:name, :string, { null: false }],
      [:city, :string],
      [:phone, :string],
      [:address, :text],
      [:cnic, :string],
      [:opening_balance, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:status, :string, { default: "active", null: false }],
    ],
  },
  {
    table: "agents",
    columns: [
      [:name, :string, { null: false }],
      [:cnic, :string],
      [:phone, :string],
      [:city, :string],
      [:address, :text],
      [:commission_type, :string, { default: "percent" }],
      [:commission_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:status, :string, { default: "active", null: false }],
    ],
  },
  {
    table: "customers",
    columns: [
      [:account_no, :string, { null: false }],
      [:name, :string, { null: false }],
      [:father_name, :string],
      [:cnic, :string],
      [:phone, :string],
      [:alt_phone, :string],
      [:address, :text],
      [:city, :string],
      [:customer_type, :string, { default: "individual" }],
      [:business_name, :string],
      [:email, :string],
      [:credit_limit, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:opening_balance, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:agent_id, :bigint],
      [:salesman_id, :bigint],
      [:status, :string, { default: "active", null: false }],
      [:is_defaulter, :boolean, { default: false }],
      [:photo_filename, :string],
      [:remarks, :text],
    ],
    indexes: [
      ["customers", ["account_no"], { unique: true }],
      ["customers", ["name"]],
      ["customers", ["phone"]],
      ["customers", ["cnic"]],
    ],
  },

  # ------------------------------------------------------------- accounting
  {
    table: "chart_of_accounts",
    columns: [
      [:code, :string, { null: false }],
      [:name, :string, { null: false }],
      [:account_type, :string, { null: false }],
      [:parent_id, :bigint],
      [:is_cash_account, :boolean, { default: false }],
      [:status, :string, { default: "active", null: false }],
    ],
    indexes: [
      ["chart_of_accounts", ["code"], { unique: true }],
      ["chart_of_accounts", ["parent_id"]],
    ],
  },
  {
    table: "ledger_entries",
    comment: "Double-entry backbone. Every money movement writes one balanced pair.",
    columns: [
      [:entry_date, :date, { null: false }],
      [:account_id, :bigint, { null: false }],
      [:debit, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:credit, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:source_type, :string],
      [:source_id, :bigint],
      [:source_no, :string],
      [:party_type, :string],
      [:party_id, :bigint],
      [:particulars, :string],
      [:remarks, :text],
      [:created_by_id, :bigint],
    ],
    indexes: [
      ["ledger_entries", ["account_id"]],
      ["ledger_entries", ["entry_date"]],
      ["ledger_entries", ["source_type", "source_id"]],
      ["ledger_entries", ["party_type", "party_id"]],
    ],
  },

  # ----------------------------------------------------------------- sales
  {
    table: "sales",
    columns: [
      [:sale_no, :string, { null: false }],
      [:sale_date, :date, { null: false }],
      [:customer_id, :bigint, { null: false }],
      [:sale_type, :string, { default: "credit", null: false }],
      [:product_id, :bigint],
      [:variant_id, :bigint],
      [:stock_unit_id, :bigint],
      [:reg_no, :string],
      [:total_amount, :decimal, { precision: 15, scale: 2, default: 0, null: false }],
      [:discount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:down_payment, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:financed_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:months, :integer, { default: 0 }],
      [:monthly_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:profit_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:payment_mode_id, :bigint],
      [:agent_id, :bigint],
      [:salesman_id, :bigint],
      [:late_fee_type, :string, { default: "none" }],
      [:status, :string, { default: "completed", null: false }],
      [:notes, :text],
      [:created_by_id, :bigint],
    ],
    indexes: [
      ["sales", ["sale_no"], { unique: true }],
      ["sales", ["customer_id"]],
      ["sales", ["sale_date"]],
      ["sales", ["status"]],
    ],
  },
  {
    table: "sale_items",
    columns: [
      [:sale_id, :bigint, { null: false }],
      [:product_id, :bigint],
      [:variant_id, :bigint],
      [:stock_unit_id, :bigint],
      [:description, :string],
      [:qty, :decimal, { precision: 12, scale: 2, default: 1 }],
      [:unit_price, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:discount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:total, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:serial_no, :string],
    ],
    indexes: [["sale_items", ["sale_id"]]],
  },
  {
    table: "installment_plans",
    columns: [
      [:sale_id, :bigint, { null: false }],
      [:installment_no, :integer, { null: false }],
      [:due_date, :date, { null: false }],
      [:amount, :decimal, { precision: 15, scale: 2, default: 0, null: false }],
      [:paid_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:short_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:late_fee, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:status, :string, { default: "pending", null: false }],
      [:paid_date, :date],
    ],
    indexes: [
      ["installment_plans", ["sale_id"]],
      ["installment_plans", ["due_date"]],
      ["installment_plans", ["status"]],
    ],
  },
  {
    table: "installment_payments",
    columns: [
      [:installment_plan_id, :bigint],
      [:sale_id, :bigint, { null: false }],
      [:customer_id, :bigint, { null: false }],
      [:payment_date, :date, { null: false }],
      [:amount, :decimal, { precision: 15, scale: 2, default: 0, null: false }],
      [:late_fee, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:is_short, :boolean, { default: false }],
      [:payment_mode_id, :bigint],
      [:reference, :string],
      [:remarks, :string],
      [:created_by_id, :bigint],
    ],
    indexes: [
      ["installment_payments", ["sale_id"]],
      ["installment_payments", ["customer_id"]],
      ["installment_payments", ["payment_date"]],
    ],
  },
  {
    table: "installment_reminders",
    columns: [
      [:installment_plan_id, :bigint, { null: false }],
      [:sale_id, :bigint],
      [:customer_id, :bigint],
      [:channel, :string, { default: "sms" }],
      [:sent_at, :datetime, { default: -> { "CURRENT_TIMESTAMP" } }],
      [:remarks, :string],
      [:created_by_id, :bigint],
    ],
    indexes: [["installment_reminders", ["installment_plan_id"]]],
  },
  {
    table: "quotations",
    columns: [
      [:quotation_no, :string, { null: false }],
      [:quotation_date, :date, { null: false }],
      [:valid_until, :date],
      [:customer_id, :bigint],
      [:customer_name, :string],
      [:customer_phone, :string],
      [:product_id, :bigint],
      [:variant_id, :bigint],
      [:sale_price, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:down_payment, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:months, :integer, { default: 0 }],
      [:monthly_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:status, :string, { default: "draft", null: false }],
      [:notes, :text],
      [:converted_sale_id, :bigint],
      [:created_by_id, :bigint],
    ],
    indexes: [
      ["quotations", ["quotation_no"], { unique: true }],
      ["quotations", ["status"]],
    ],
  },
  {
    table: "quotation_plans",
    columns: [
      [:quotation_id, :bigint, { null: false }],
      [:installment_no, :integer, { null: false }],
      [:due_date, :date, { null: false }],
      [:amount, :decimal, { precision: 15, scale: 2, default: 0 }],
    ],
    indexes: [["quotation_plans", ["quotation_id"]]],
  },

  # -------------------------------------------------------------- purchase
  {
    table: "purchases",
    columns: [
      [:purchase_no, :string, { null: false }],
      [:purchase_date, :date, { null: false }],
      [:supplier_id, :bigint, { null: false }],
      [:invoice_no, :string],
      [:subtotal, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:discount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:total_amount, :decimal, { precision: 15, scale: 2, default: 0, null: false }],
      [:paid_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:payment_type, :string, { default: "credit" }],
      [:payment_mode_id, :bigint],
      [:status, :string, { default: "completed", null: false }],
      [:notes, :text],
      [:created_by_id, :bigint],
    ],
    indexes: [
      ["purchases", ["purchase_no"], { unique: true }],
      ["purchases", ["supplier_id"]],
      ["purchases", ["purchase_date"]],
    ],
  },
  {
    table: "purchase_items",
    columns: [
      [:purchase_id, :bigint, { null: false }],
      [:product_id, :bigint],
      [:variant_id, :bigint],
      [:description, :string],
      [:qty, :decimal, { precision: 12, scale: 2, default: 1 }],
      [:unit_price, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:total, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:create_stock_unit, :boolean, { default: true }],
      [:engine_no, :string],
      [:chassis_no, :string],
    ],
    indexes: [["purchase_items", ["purchase_id"]]],
  },
  {
    table: "purchase_payments",
    columns: [
      [:purchase_id, :bigint, { null: false }],
      [:payment_date, :date, { null: false }],
      [:amount, :decimal, { precision: 15, scale: 2, default: 0, null: false }],
      [:payment_mode_id, :bigint],
      [:reference, :string],
      [:remarks, :string],
      [:created_by_id, :bigint],
    ],
    indexes: [["purchase_payments", ["purchase_id"]]],
  },
  {
    table: "stock_units",
    columns: [
      [:product_id, :bigint],
      [:variant_id, :bigint],
      [:purchase_item_id, :bigint],
      [:purchase_id, :bigint],
      [:sale_id, :bigint],
      [:supplier_id, :bigint],
      [:engine_no, :string],
      [:chassis_no, :string],
      [:challan_no, :string],
      [:reg_no, :string],
      [:serial_no, :string],
      [:biometric, :string],
      [:file_location, :string],
      [:colour, :string],
      [:warranty_months, :integer, { default: 0 }],
      [:warranty_expiry, :date],
      [:cost_price, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:sale_price, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:status, :string, { default: "available", null: false }],
      [:date_added, :date, { default: -> { "CURRENT_DATE" } }],
      [:sold_on, :date],
      [:remarks, :text],
    ],
    indexes: [
      ["stock_units", ["status"]],
      ["stock_units", ["engine_no"]],
      ["stock_units", ["chassis_no"]],
      ["stock_units", ["product_id"]],
      ["stock_units", ["variant_id"]],
    ],
  },

  # -------------------------------------------------------------- vouchers
  {
    table: "vouchers",
    comment: "Receipt and payment vouchers share one table; kind is receipt|payment.",
    columns: [
      [:kind, :string, { null: false }],
      [:voucher_no, :string, { null: false }],
      [:voucher_date, :date, { null: false }],
      [:party_type, :string],
      [:party_id, :bigint],
      [:party_name, :string],
      [:account_id, :bigint],
      [:amount, :decimal, { precision: 15, scale: 2, default: 0, null: false }],
      [:payment_mode_id, :bigint],
      [:reference, :string],
      [:remarks, :string],
      [:created_by_id, :bigint],
    ],
    indexes: [
      ["vouchers", ["voucher_no", "kind"], { unique: true }],
      ["vouchers", ["voucher_date"]],
      ["vouchers", ["party_type", "party_id"]],
    ],
  },
  {
    table: "journal_vouchers",
    columns: [
      [:voucher_no, :string, { null: false }],
      [:voucher_date, :date, { null: false }],
      [:description, :string],
      [:total_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:reference, :string],
      [:status, :string, { default: "posted", null: false }],
      [:posted_by_id, :bigint],
      [:posted_at, :datetime],
    ],
    indexes: [["journal_vouchers", ["voucher_no"], { unique: true }]],
  },
  {
    table: "journal_voucher_lines",
    columns: [
      [:journal_voucher_id, :bigint, { null: false }],
      [:account_id, :bigint, { null: false }],
      [:debit, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:credit, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:remarks, :string],
      [:line_no, :integer, { default: 1 }],
    ],
    indexes: [["journal_voucher_lines", ["journal_voucher_id"]]],
  },
  {
    table: "expenses",
    columns: [
      [:expense_date, :date, { null: false }],
      [:category_id, :bigint],
      [:description, :string],
      [:amount, :decimal, { precision: 15, scale: 2, default: 0, null: false }],
      [:payment_mode_id, :bigint],
      [:account_id, :bigint],
      [:reference, :string],
      [:added_by_id, :bigint],
    ],
    indexes: [
      ["expenses", ["expense_date"]],
      ["expenses", ["category_id"]],
    ],
  },
  {
    table: "cash_book_entries",
    columns: [
      [:entry_date, :date, { null: false }],
      [:direction, :string, { null: false }],
      [:particulars, :string],
      [:source_type, :string],
      [:source_id, :bigint],
      [:source_no, :string],
      [:amount, :decimal, { precision: 15, scale: 2, default: 0, null: false }],
      [:payment_mode_id, :bigint],
      [:account_id, :bigint],
      [:created_by_id, :bigint],
    ],
    indexes: [
      ["cash_book_entries", ["entry_date"]],
      ["cash_book_entries", ["source_type", "source_id"]],
    ],
  },

  # ------------------------------------------- customer accounts / recovery
  {
    table: "account_transfers",
    columns: [
      [:transfer_date, :date, { null: false }],
      [:customer_id, :bigint, { null: false }],
      [:from_customer_id, :bigint, { null: false }],
      [:to_customer_id, :bigint, { null: false }],
      [:sale_id, :bigint],
      [:stock_unit_id, :bigint],
      [:remaining_balance, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:fee, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:status, :string, { default: "pending" }],
      [:remarks, :text],
      [:created_by_id, :bigint],
    ],
    indexes: [["account_transfers", ["from_customer_id"]]],
  },
  {
    table: "account_closures",
    columns: [
      [:closure_date, :date, { null: false }],
      [:customer_id, :bigint, { null: false }],
      [:sale_id, :bigint],
      [:remaining_balance, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:settled_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:waived_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:reason, :string],
      [:status, :string, { default: "completed" }],
      [:created_by_id, :bigint],
    ],
    indexes: [["account_closures", ["customer_id"]]],
  },
  {
    table: "post_dated_cheques",
    columns: [
      [:cheque_no, :string, { null: false }],
      [:bank_name, :string],
      [:customer_id, :bigint, { null: false }],
      [:sale_id, :bigint],
      [:account_no, :string],
      [:amount, :decimal, { precision: 15, scale: 2, default: 0, null: false }],
      [:cheque_date, :date, { null: false }],
      [:covered_month, :date],
      [:status, :string, { default: "pending", null: false }],
      [:deposited_on, :date],
      [:remarks, :string],
      [:created_by_id, :bigint],
    ],
    indexes: [
      ["post_dated_cheques", ["status"]],
      ["post_dated_cheques", ["cheque_no"]],
    ],
  },
  {
    table: "credit_recoveries",
    columns: [
      [:recovery_date, :date, { null: false }],
      [:sale_id, :bigint, { null: false }],
      [:customer_id, :bigint, { null: false }],
      [:agreed_date, :date],
      [:amount, :decimal, { precision: 15, scale: 2, default: 0, null: false }],
      [:payment_mode_id, :bigint],
      [:reference, :string],
      [:remarks, :string],
      [:created_by_id, :bigint],
    ],
    indexes: [
      ["credit_recoveries", ["sale_id"]],
      ["credit_recoveries", ["recovery_date"]],
    ],
  },

  # --------------------------------------------------------------- bookings
  {
    table: "advance_bookings",
    columns: [
      [:booking_no, :string, { null: false }],
      [:booking_date, :date, { null: false }],
      [:customer_id, :bigint],
      [:customer_name, :string],
      [:customer_phone, :string],
      [:product_id, :bigint],
      [:variant_id, :bigint],
      [:stock_unit_id, :bigint],
      [:sale_type, :string, { default: "credit" }],
      [:total_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:advance_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:balance_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:months, :integer, { default: 0 }],
      [:monthly_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:expected_delivery, :date],
      [:late_fee_type, :string, { default: "none" }],
      [:agent_id, :bigint],
      [:status, :string, { default: "confirmed", null: false }],
      [:remarks, :text],
      [:created_by_id, :bigint],
    ],
    indexes: [
      ["advance_bookings", ["booking_no"], { unique: true }],
      ["advance_bookings", ["status"]],
    ],
  },
  {
    table: "advance_booking_payments",
    columns: [
      [:advance_booking_id, :bigint, { null: false }],
      [:payment_date, :date, { null: false }],
      [:amount, :decimal, { precision: 15, scale: 2, default: 0, null: false }],
      [:payment_mode_id, :bigint],
      [:remarks, :string],
      [:created_by_id, :bigint],
    ],
    indexes: [["advance_booking_payments", ["advance_booking_id"]]],
  },
  {
    table: "advance_booking_plans",
    columns: [
      [:advance_booking_id, :bigint, { null: false }],
      [:installment_no, :integer, { null: false }],
      [:due_date, :date, { null: false }],
      [:amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:paid_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:status, :string, { default: "pending" }],
    ],
    indexes: [["advance_booking_plans", ["advance_booking_id"]]],
  },

  # ---------------------------------------------------------- registration
  {
    table: "registration_trackings",
    columns: [
      [:sale_id, :bigint, { null: false }],
      [:customer_id, :bigint, { null: false }],
      [:agent_id, :bigint],
      [:engine_no, :string],
      [:chassis_no, :string],
      [:submitted_date, :date],
      [:expected_return_date, :date],
      [:letter_received, :boolean, { default: false }],
      [:received_date, :date],
      [:status, :string, { default: "pending", null: false }],
      [:remarks, :text],
      [:created_by_id, :bigint],
    ],
    indexes: [
      ["registration_trackings", ["sale_id"], { unique: true }],
      ["registration_trackings", ["status"]],
    ],
  },
  {
    table: "vehicle_documents",
    columns: [
      [:sale_id, :bigint, { null: false }],
      [:customer_id, :bigint],
      [:document_type, :string, { null: false }],
      [:reference_no, :string],
      [:received, :boolean, { default: false }],
      [:remarks, :string],
      [:created_by_id, :bigint],
    ],
    indexes: [
      ["vehicle_documents", ["sale_id"]],
      ["vehicle_documents", ["document_type"]],
    ],
  },

  # ------------------------------------------------------------ commissions
  {
    table: "agent_commissions",
    columns: [
      [:agent_id, :bigint, { null: false }],
      [:sale_id, :bigint, { null: false }],
      [:customer_id, :bigint],
      [:sale_date, :date],
      [:sale_no, :string],
      [:basis_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:commission_type, :string, { default: "percent" }],
      [:commission_value, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:earned_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:paid_amount, :decimal, { precision: 15, scale: 2, default: 0 }],
      [:status, :string, { default: "pending" }],
    ],
    indexes: [
      ["agent_commissions", ["agent_id"]],
      ["agent_commissions", ["sale_id"], { unique: true }],
    ],
  },
  {
    table: "agent_commission_payments",
    columns: [
      [:agent_commission_id, :bigint, { null: false }],
      [:payment_date, :date, { null: false }],
      [:amount, :decimal, { precision: 15, scale: 2, default: 0, null: false }],
      [:payment_mode_id, :bigint],
      [:remarks, :string],
      [:created_by_id, :bigint],
    ],
    indexes: [["agent_commission_payments", ["agent_commission_id"]]],
  },
]
